/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author Augusto Winkler
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinNumero = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        txtRestoPor2 = new javax.swing.JLabel();
        txtAoCubo = new javax.swing.JLabel();
        txtRaizQuadrada = new javax.swing.JLabel();
        txtRaizCubica = new javax.swing.JLabel();
        txtValorAbsoluto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblRestoPor2 = new javax.swing.JLabel();
        lblAoCubo = new javax.swing.JLabel();
        lblRaizQuadrada = new javax.swing.JLabel();
        lblRaizCubica = new javax.swing.JLabel();
        lblValorAbsoluto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Super Calculadora");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 12, -1, -1));

        jLabel2.setText("Informe um valor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, -1, -1));
        getContentPane().add(spinNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 69, 80, -1));

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 56, 120, -1));

        txtRestoPor2.setText(" ");
        getContentPane().add(txtRestoPor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 94, -1));

        txtAoCubo.setText(" ");
        getContentPane().add(txtAoCubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, 94, -1));

        txtRaizQuadrada.setBackground(new java.awt.Color(255, 255, 255));
        txtRaizQuadrada.setText(" ");
        getContentPane().add(txtRaizQuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 157, 94, -1));

        txtRaizCubica.setText(" ");
        getContentPane().add(txtRaizCubica, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 179, 94, -1));

        txtValorAbsoluto.setText(" ");
        getContentPane().add(txtValorAbsoluto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 201, 94, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblRestoPor2.setText(" ");

        lblAoCubo.setText(" ");

        lblRaizQuadrada.setText(" ");

        lblRaizCubica.setText(" ");

        lblValorAbsoluto.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAoCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRaizCubica, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRestoPor2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblRestoPor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAoCubo)
                .addGap(6, 6, 6)
                .addComponent(lblRaizQuadrada)
                .addGap(6, 6, 6)
                .addComponent(lblRaizCubica)
                .addGap(6, 6, 6)
                .addComponent(lblValorAbsoluto)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 360, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
       int N = (int) spinNumero.getValue();
       int resto = N % 2;
       int aoCubo = (int) Math.pow(N, 3);
       float raizQuadrada = (float) Math.sqrt(N);
       float raizCubica = (float) Math.cbrt(N);
       int absoluto = (int) Math.abs(N);
       
       txtRestoPor2.setText("Resto da Divisão por 2:");
       lblRestoPor2.setText(Integer.toString(resto));
       
       txtAoCubo.setText("Elevado ao Cubo:");
       lblAoCubo.setText(Integer.toString(aoCubo));
       
       txtRaizQuadrada.setText("Raiz Quadrada:");
       lblRaizQuadrada.setText(Float.toString(raizQuadrada));
       
       txtRaizCubica.setText("Raiz Cubica:");
       lblRaizCubica.setText(Float.toString(raizCubica));
     
       txtValorAbsoluto.setText("Valor Absoluto:");
       lblValorAbsoluto.setText(Integer.toString(absoluto));
        
       
       
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAoCubo;
    private javax.swing.JLabel lblRaizCubica;
    private javax.swing.JLabel lblRaizQuadrada;
    private javax.swing.JLabel lblRestoPor2;
    private javax.swing.JLabel lblValorAbsoluto;
    private javax.swing.JSpinner spinNumero;
    private javax.swing.JLabel txtAoCubo;
    private javax.swing.JLabel txtRaizCubica;
    private javax.swing.JLabel txtRaizQuadrada;
    private javax.swing.JLabel txtRestoPor2;
    private javax.swing.JLabel txtValorAbsoluto;
    // End of variables declaration//GEN-END:variables
}
